"""add_node_roles

Revision ID: 0d522720a63d
Revises: 43cb03f7ac49
Create Date: 2026-05-24 20:37:07.691556

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d522720a63d"
down_revision: Union[str, Sequence[str], None] = "43cb03f7ac49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "nodes", ["upstream_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
