"""add node_stats table

Revision ID: 43cb03f7ac49
Revises: 7317e3316e78
Create Date: 2026-05-24 19:33:40.928079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43cb03f7ac49"
down_revision: Union[str, Sequence[str], None] = "7317e3316e78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("cpu_ema", sa.Float(), nullable=False),
        sa.Column("rx_bps", sa.Float(), nullable=False),
        sa.Column("tx_bps", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("node_stats")
    # ### end Alembic commands ###
