"""add_client_sub_token

Revision ID: 8452a9308f45
Revises: 0d522720a63d
Create Date: 2026-05-24 22:02:12.124351

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8452a9308f45"
down_revision: Union[str, Sequence[str], None] = "0d522720a63d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_token", sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column("sub_enabled", sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f("ix_clients_sub_token"), ["sub_token"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clients_sub_token"))
        batch_op.drop_column("sub_enabled")
        batch_op.drop_column("sub_token")

    # ### end Alembic commands ###
